image: openjdk:17

stages:
  - run

variables:
  DOCKER_DRIVER: overlay

before_script:
  - chmod +x ./runPipeline.sh
  - chmod +x ./gradlew

run_pipeline:
  stage: run

  script:
    - ./runPipeline.sh
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      - build/reports